# Karakeep (bookmark-everything app), migrated off the Hetzner k8s cluster
# (migrate-karakeep.sh). Design archived in the Homecluster/NixOS wiki (Specs).
#
# SQLite-only (no PostgreSQL support upstream), so NOT a tenant of the shared
# cluster. The module also brings up Meilisearch (default keyless localhost
# instance) and a sandboxed headless Chromium (screenshots, :9222).
#
# Storage: DB + irreplaceable assets/ on the fast pool at
# /srv/fast/appdata/karakeep, bind-mounted onto /var/lib/karakeep (see the
# storage block below). restic sweeps it offsite; a 02:45 timer first writes
# consistent exports so the offsite copy never depends on the live WAL db.
#
# Secret: OPENAI_API_KEY (AI tagging + LLM OCR) via op-secrets.
# NEXTAUTH_SECRET / MEILI_MASTER_KEY are auto-generated by karakeep-init.
{ pkgs, ... }:
{
  opSecrets.karakeep = {
    template = ./karakeep.env.tpl;
    path = "/var/lib/secrets/karakeep.env";
    owner = "karakeep";
  };

  services.karakeep = {
    enable = true;
    # No `package` override: karakeep's better-sqlite3 core-dumps on Node 24
    # (karakeep-app/karakeep#2989), but nixpkgs now pins nodejs_22 itself and
    # the package no longer accepts a `nodejs` override arg.
    #
    # OPENAI_API_KEY for the web + workers units (workers do the inference).
    environmentFile = "/var/lib/secrets/karakeep.env";
    extraEnvironment = {
      NEXTAUTH_URL = "https://karakeep.polaris.mattiasgees.be";
      DB_WAL_MODE = "true";
      DISABLE_NEW_RELEASE_CHECK = "true"; # Nix-managed; silence the update nag.
      DISABLE_SIGNUPS = "true"; # the migrated DB already contains the admin account.
      # Carried over verbatim from the k8s ConfigMap, where gpt-4o-mini was
      # pinned "due to bug".
      INFERENCE_TEXT_MODEL = "gpt-4o-mini";
      INFERENCE_IMAGE_MODEL = "gpt-4o-mini";
      OCR_USE_LLM = "true";
    };
  };

  # sqlite3 CLI for ops: the consistency-dump unit below, the migration script
  # (migrate-karakeep.sh), and the runbook's verify steps all shell out to it.
  environment.systemPackages = [ pkgs.sqlite ];

  # Storage on the fast pool. DATA_DIR can't be repointed cleanly — the module
  # derives the migrate step's dir from StateDirectory (always
  # /var/lib/karakeep) and hardcodes /var/lib/karakeep/settings.env — so we
  # bind-mount a plain subdir of the fast/appdata dataset onto it instead.
  #
  # Hand-rolled mount unit, not a fileSystems entry: tmpfiles creates the
  # source *after* local-fs.target, while a fileSystems bind mounts *at*
  # local-fs.target and would bind an empty/missing dir. outline.nix reuses
  # this pattern.
  systemd.tmpfiles.rules = [
    "d /srv/fast/appdata/karakeep 0700 karakeep karakeep - -"
  ];
  systemd.mounts = [{
    what = "/srv/fast/appdata/karakeep";
    where = "/var/lib/karakeep";
    type = "none";
    options = "bind";
    # DefaultDependencies=no is REQUIRED. A normal mount is ordered Before
    # local-fs.target, but tmpfiles-setup runs After it, so requiring
    # tmpfiles-setup forms a cycle (mount → tmpfiles-setup → local-fs.target →
    # mount). systemd 261 breaks it by dropping the mount job, silently leaving
    # /var/lib/karakeep unmounted and every karakeep unit dead. Without default
    # deps it becomes a late mount pulled in by multi-user.target; the
    # umount.target lines restore a clean unmount ahead of ZFS at shutdown.
    unitConfig.DefaultDependencies = false;
    requires = [ "systemd-tmpfiles-setup.service" ];
    after = [ "systemd-tmpfiles-setup.service" ];
    before = [ "umount.target" ];
    conflicts = [ "umount.target" ];
    wantedBy = [ "multi-user.target" ];
  }];

  # Never let a karakeep unit start (and write into the empty underlying
  # /var/lib/karakeep on the root disk) before the bind mount is up.
  systemd.services.karakeep-init.unitConfig.RequiresMountsFor = "/var/lib/karakeep";
  systemd.services.karakeep-workers.unitConfig.RequiresMountsFor = "/var/lib/karakeep";
  systemd.services.karakeep-web.unitConfig.RequiresMountsFor = "/var/lib/karakeep";

  # Consistent exports before the 03:00 restic run: a WAL-aware binary .backup
  # (exact, fast restore) and a portable gzipped .dump (inspectable).
  systemd.services.karakeep-sqlite-backup = {
    description = "Consistent SQLite exports of Karakeep DB for backup";
    after = [ "karakeep-web.service" ];
    unitConfig.RequiresMountsFor = "/var/lib/karakeep";
    path = [ pkgs.sqlite pkgs.gzip ];
    serviceConfig = {
      Type = "oneshot";
      User = "karakeep";
      Group = "karakeep";
      StateDirectory = "karakeep";
      ExecStart = pkgs.writeShellScript "karakeep-sqlite-backup" ''
        set -euo pipefail
        db=/var/lib/karakeep/db.db
        out=/var/lib/karakeep/backups
        # First boot / pre-migration: no DB yet — nothing to export.
        [ -f "$db" ] || { echo "karakeep db not present yet: $db"; exit 0; }
        install -d -m 0700 "$out"
        sqlite3 "$db" ".backup '$out/db.db'"
        sqlite3 "$db" ".dump" | gzip -c > "$out/db.sql.gz"
      '';
    };
  };
  systemd.timers.karakeep-sqlite-backup = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "02:45"; # ahead of the 03:00 restic sweep
      Persistent = true;
    };
  };
}
