# Karakeep (self-hostable bookmark-everything app), migrated off the Hetzner
# Kubernetes cluster. Design archived in the Homecluster/NixOS wiki (Specs);
# operator steps live in docs/polaris/setup.md (Karakeep section, Part 2 §5).
#
# Unlike Immich/Miniflux, Karakeep is **SQLite-only** — there is no PostgreSQL
# support (upstream: the DB lives in DATA_DIR; the module bundles better-sqlite3),
# so it is NOT a tenant of the shared pg18 cluster. `services.karakeep.enable`
# also brings up Meilisearch (full-text search, kept on its default keyless
# localhost instance) and a sandboxed headless Chromium (screenshots, :9222).
#
# Storage: the SQLite DB + the irreplaceable assets/ live on the **fast** pool
# (mirrored, encrypted NVMe) at /srv/fast/appdata/karakeep — a plain subdir of the
# existing fast/appdata dataset, created by tmpfiles and bind-mounted onto
# /var/lib/karakeep. DATA_DIR is hardcoded there and can't be repointed cleanly
# (see the storage block below), so we back the path instead of moving it.
#
# Backup: /srv/fast/appdata is swept offsite by modules/server/restic.nix. A 02:45
# timer additionally writes a consistent .backup (binary) + .dump (portable SQL)
# into backups/ before the 03:00 restic run, so the offsite copy always has a
# clean DB even though restic also sweeps the live (WAL) db.db.
#
# Secret: OPENAI_API_KEY (AI auto-tagging + LLM OCR) is rendered from
# op://polaris/karakeep/* by op-secrets to /var/lib/secrets/karakeep.env.
# NEXTAUTH_SECRET / MEILI_MASTER_KEY are auto-generated by karakeep-init.
{ pkgs, ... }:
{
  opSecrets.karakeep = {
    template = ./karakeep.env.tpl;
    path = "/var/lib/secrets/karakeep.env";
    owner = "karakeep";
  };

  services.karakeep = {
    enable = true;
    # Build karakeep against Node 22. karakeep pins better-sqlite3 11.3.0, and
    # better-sqlite3 < 12.0.0 has no Node 24 support — under nixpkgs' nodejs-24.19.0
    # the workers process core-dumps at startup (native Statement::~Statement ->
    # node::RemoveEnvironmentCleanupHook, (env) != nullptr), a known Node-24.19.0
    # regression. Node 22 avoids it. Drop this once karakeep ships better-sqlite3 >= 12.
    package = pkgs.karakeep.override { nodejs = pkgs.nodejs_22; };
    # OPENAI_API_KEY (op-secrets). The module feeds this to the web + workers
    # units; the workers do the inference.
    environmentFile = "/var/lib/secrets/karakeep.env";
    extraEnvironment = {
      NEXTAUTH_URL = "https://karakeep.polaris.mattiasgees.be";
      DB_WAL_MODE = "true";
      DISABLE_NEW_RELEASE_CHECK = "true"; # Nix-managed; silence the update nag.
      DISABLE_SIGNUPS = "true"; # the migrated DB already contains the admin account.
      # AI settings carried over verbatim from the k8s ConfigMap. gpt-4o-mini is
      # pinned upstream "due to bug" — see the k8s config we migrated from.
      INFERENCE_TEXT_MODEL = "gpt-4o-mini";
      INFERENCE_IMAGE_MODEL = "gpt-4o-mini";
      OCR_USE_LLM = "true";
    };
  };

  # sqlite3 CLI for ops: the consistency-dump unit below, the migration script
  # (migrate-karakeep.sh), and the runbook's verify steps all shell out to it.
  environment.systemPackages = [ pkgs.sqlite ];

  # Put the data on the fast pool. DATA_DIR can't be repointed cleanly — the
  # module derives the migrate step's dir from StateDirectory (always
  # /var/lib/karakeep) and hardcodes the secrets file at
  # /var/lib/karakeep/settings.env — so /var/lib/karakeep is unavoidable and we
  # back it with a bind mount instead.
  #
  # No dedicated dataset: /srv/fast/appdata/karakeep is a plain subdir of the
  # existing fast/appdata dataset (same as bazarr/sonarr/…), created by tmpfiles
  # and owned by the karakeep user. It stays under /srv/fast/appdata, so the
  # restic sweep in modules/server/restic.nix already covers it.
  #
  # The bind is a hand-rolled mount unit (not a fileSystems entry) on purpose:
  # tmpfiles creates the subdir *after* local-fs.target, but a fileSystems bind
  # mounts *at* local-fs.target — it would race tmpfiles and bind an empty dir.
  # Ordering this mount After systemd-tmpfiles-setup guarantees the source exists
  # first; the karakeep units' RequiresMountsFor (below) then wait on this mount.
  systemd.tmpfiles.rules = [
    "d /srv/fast/appdata/karakeep 0700 karakeep karakeep - -"
  ];
  systemd.mounts = [{
    what = "/srv/fast/appdata/karakeep";
    where = "/var/lib/karakeep";
    type = "none";
    options = "bind";
    requires = [ "systemd-tmpfiles-setup.service" ];
    after = [ "systemd-tmpfiles-setup.service" ];
    wantedBy = [ "multi-user.target" ];
  }];

  # Belt-and-suspenders: never let a karakeep unit start (and write to the empty
  # underlying /var/lib/karakeep on the root disk) before the bind mount is up.
  systemd.services.karakeep-init.unitConfig.RequiresMountsFor = "/var/lib/karakeep";
  systemd.services.karakeep-workers.unitConfig.RequiresMountsFor = "/var/lib/karakeep";
  systemd.services.karakeep-web.unitConfig.RequiresMountsFor = "/var/lib/karakeep";

  # Backup: /srv/fast/appdata (which contains this data) is swept offsite by
  # modules/server/restic.nix — no per-app restic path needed here.

  # Consistency exports before the 03:00 restic run: a WAL-aware binary .backup
  # (exact, fast restore) and a portable gzipped .dump (format-independent,
  # inspectable). Both land under the restic-swept /srv/fast/appdata path.
  systemd.services.karakeep-sqlite-backup = {
    description = "Consistent SQLite exports of Karakeep DB for backup";
    after = [ "karakeep-web.service" ];
    unitConfig.RequiresMountsFor = "/var/lib/karakeep";
    path = [ pkgs.sqlite pkgs.gzip ];
    serviceConfig = {
      Type = "oneshot";
      User = "karakeep";
      Group = "karakeep";
      StateDirectory = "karakeep";
      ExecStart = pkgs.writeShellScript "karakeep-sqlite-backup" ''
        set -euo pipefail
        db=/var/lib/karakeep/db.db
        out=/var/lib/karakeep/backups
        # First boot / pre-migration: no DB yet — nothing to export.
        [ -f "$db" ] || { echo "karakeep db not present yet: $db"; exit 0; }
        install -d -m 0700 "$out"
        sqlite3 "$db" ".backup '$out/db.db'"
        sqlite3 "$db" ".dump" | gzip -c > "$out/db.sql.gz"
      '';
    };
  };
  systemd.timers.karakeep-sqlite-backup = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "02:45"; # ahead of the 03:00 restic sweep in restic.nix
      Persistent = true; # run on next boot if the box was off at 02:45
    };
  };
}
