# Karakeep (self-hostable bookmark-everything app), migrated off the Hetzner
# Kubernetes cluster. See docs/superpowers/specs/2026-08-15-polaris-karakeep-design.md
# and the operator runbook docs/polaris/karakeep-migration-runbook.md.
#
# Unlike Immich/Miniflux, Karakeep is **SQLite-only** — there is no PostgreSQL
# support (upstream: the DB lives in DATA_DIR; the module bundles better-sqlite3),
# so it is NOT a tenant of the shared pg18 cluster. `services.karakeep.enable`
# also brings up Meilisearch (full-text search, kept on its default keyless
# localhost instance) and a sandboxed headless Chromium (screenshots, :9222).
#
# Storage: the SQLite DB + the irreplaceable assets/ live on the **fast** pool
# (mirrored, encrypted NVMe) at /srv/fast/appdata/karakeep. The module hardcodes
# DATA_DIR=/var/lib/karakeep and derives the migrate step's dir from
# StateDirectory (also /var/lib/karakeep), so overriding DATA_DIR desyncs the two
# and is unsupported — instead we **bind-mount** the dataset onto /var/lib/karakeep
# and leave the module untouched.
#
# Backup: /srv/fast/appdata/karakeep is outside the /srv/data restic sweep, so it
# is added to the restic path explicitly below. A 02:45 timer writes a consistent
# .backup (binary) + .dump (portable SQL) into backups/ before the 03:00 restic
# run, so the offsite copy always has a clean DB even though restic also sweeps
# the live (WAL) db.db.
#
# Secret: OPENAI_API_KEY (AI auto-tagging + LLM OCR) is hand-placed at
# /etc/karakeep/karakeep.env (0600, out of git) — see manual-steps.md §12.
# NEXTAUTH_SECRET / MEILI_MASTER_KEY are auto-generated by karakeep-init.
{ pkgs, ... }:
{
  services.karakeep = {
    enable = true;
    # OPENAI_API_KEY (hand-placed). The module feeds this to the web + workers
    # units; the workers do the inference.
    environmentFile = "/etc/karakeep/karakeep.env";
    extraEnvironment = {
      NEXTAUTH_URL = "https://karakeep.polaris.mattiasgees.be";
      DB_WAL_MODE = "true";
      DISABLE_NEW_RELEASE_CHECK = "true"; # Nix-managed; silence the update nag.
      DISABLE_SIGNUPS = "true"; # the migrated DB already contains the admin account.
      # AI settings carried over verbatim from the k8s ConfigMap. gpt-4o-mini is
      # pinned upstream "due to bug" — see the k8s config we migrated from.
      INFERENCE_TEXT_MODEL = "gpt-4o-mini";
      INFERENCE_IMAGE_MODEL = "gpt-4o-mini";
      OCR_USE_LLM = "true";
    };
  };

  # sqlite3 CLI for ops: the consistency-dump unit below, the migration script
  # (migrate-karakeep.sh), and the runbook's verify steps all shell out to it.
  environment.systemPackages = [ pkgs.sqlite ];

  # Data on the fast pool. DATA_DIR is pinned to /var/lib/karakeep by the module,
  # so bind the dataset there rather than repointing DATA_DIR.
  #
  # x-systemd.requires=zfs-mount.service (which implies After=) makes this bind
  # wait until ZFS has loaded keys and mounted /srv/fast/appdata/karakeep — the
  # ZFS datasets are bulk-mounted by that oneshot, not by per-dataset mount units,
  # so without this the bind can race ahead and mount the empty underlying dir.
  # (Same class of ordering care as modules/server/zfs.nix's load-zfs-keyfiles.)
  fileSystems."/var/lib/karakeep" = {
    device = "/srv/fast/appdata/karakeep";
    options = [ "bind" "x-systemd.requires=zfs-mount.service" ];
  };

  # Belt-and-suspenders: never let a karakeep unit start (and write to the empty
  # underlying /var/lib/karakeep on the root disk) before the bind mount is up.
  systemd.services.karakeep-init.unitConfig.RequiresMountsFor = "/var/lib/karakeep";
  systemd.services.karakeep-workers.unitConfig.RequiresMountsFor = "/var/lib/karakeep";
  systemd.services.karakeep-web.unitConfig.RequiresMountsFor = "/var/lib/karakeep";

  # Backup: /srv/fast/appdata (which contains this data) is swept offsite by
  # modules/server/restic.nix — no per-app restic path needed here.

  # Consistency exports before the 03:00 restic run: a WAL-aware binary .backup
  # (exact, fast restore) and a portable gzipped .dump (format-independent,
  # inspectable). Both land under the restic-swept dataset.
  systemd.services.karakeep-sqlite-backup = {
    description = "Consistent SQLite exports of Karakeep DB for backup";
    after = [ "karakeep-web.service" ];
    unitConfig.RequiresMountsFor = "/var/lib/karakeep";
    path = [ pkgs.sqlite pkgs.gzip ];
    serviceConfig = {
      Type = "oneshot";
      User = "karakeep";
      Group = "karakeep";
      StateDirectory = "karakeep";
      ExecStart = pkgs.writeShellScript "karakeep-sqlite-backup" ''
        set -euo pipefail
        db=/var/lib/karakeep/db.db
        out=/var/lib/karakeep/backups
        # First boot / pre-migration: no DB yet — nothing to export.
        [ -f "$db" ] || { echo "karakeep db not present yet: $db"; exit 0; }
        install -d -m 0700 "$out"
        sqlite3 "$db" ".backup '$out/db.db'"
        sqlite3 "$db" ".dump" | gzip -c > "$out/db.sql.gz"
      '';
    };
  };
  systemd.timers.karakeep-sqlite-backup = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "02:45"; # ahead of the 03:00 restic sweep in restic.nix
      Persistent = true; # run on next boot if the box was off at 02:45
    };
  };
}
