#! /usr/bin/env zsh

# PATH
export NIXPKGS_ALLOW_UNFREE=1
export PATH=/etc/profiles/per-user/mattias/bin:$PATH
export PATH=/Users/mattias/Library/Python/3.9/bin:$PATH
export PATH=/run/wrappers/bin:/run/current-system/sw/bin:/opt/homebrew/bin:$PATH
export PATH=/etc/profiles/per-user/mattias/bin:$PATH
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export DOCKER_HOST="unix://$HOME/.colima/docker.sock"
# Defaults
export SHELL=zsh
export EDITOR='nvim'
export DEFAULT_USER=mattias
export WLR_DRM_NO_MODIFIERS=1
# Directory Env Vars
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin

# Google Cloud GKE
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

export KUBECONFIG=$HOME/.kube/config

# set virtualenvwrapper to global python3
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3

# SSH
# export SSH_ASKPASS="/etc/profiles/per-user/mattias/bin/ksshaskpass"
export SSH_ASKPASS_REQUIRE="force"

# COSIGN
export CK=$HOME/.cosign/cosign.key
export CP=$HOME/.cosign/cosign.pub

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# use ripgrep for fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# That stupid thing I need for GPG
export GPG_TTY=$(tty)

# Tailscale dev
export TAILSCALE_REPO="$HOME/Git/tailscale"
export CORP_REPO="$HOME/Git/corp"
export VALUES_FILE="$HOME/Git/tailscale/mattias/values.yaml"
export REGISTRY="europe-west2-docker.pkg.dev/tailscale-sandbox/mattias"
