#!/usr/bin/env bash
#
#  Homebrew-only setup of the tiling WM stack (yabai, skhd, JankyBorders,
#  sketchybar) for Macs that can't run nix-darwin, e.g. a managed work laptop.
#
#  Mirrors services.{yabai,skhd,jankyborders} in darwin/configuration.nix —
#  keep the two in sync. Differences from the nix-darwin setup:
#    - No yabai scripting addition (needs SIP disabled). Without it, moving
#      windows between spaces, space focus from sketchybar and sub-layer rules
#      don't work. The SA isn't loaded on the nix Macs either while SIP is on.
#    - Services run under the tools' own launchd labels, so the skhd restart
#      bindings use `--restart-service` / `brew services` instead of org.nixos.*.
#    - `layer=` is `sub-layer=` (yabai 6+), and the removed window_border*
#      options are left out (JankyBorders draws the borders).
#
#  Run from a checkout of this repo as your normal user (not sudo). Re-running
#  is safe: existing configs that differ are moved aside to *.backup.
#  ~/.config/sketchybar is symlinked into the checkout, so edits there apply
#  without re-running this.
#

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }

[[ "$(uname)" == Darwin ]] || { echo "macOS only" >&2; exit 1; }
[[ $EUID -ne 0 ]] || { echo "run as your user, not root" >&2; exit 1; }
command -v brew >/dev/null || { echo "Homebrew not found: https://brew.sh" >&2; exit 1; }
xcode-select -p >/dev/null 2>&1 || {
  echo "Xcode Command Line Tools are needed (SbarLua and the sketchybar helpers are compiled): xcode-select --install" >&2
  exit 1
}

# Write stdin to $1, moving a differing existing file to $1.backup.
install_file() {
  local dest="$1" mode="$2" tmp
  tmp="$(mktemp)"
  cat >"$tmp"
  mkdir -p "$(dirname "$dest")"
  if [[ -e "$dest" || -L "$dest" ]] && ! cmp -s "$tmp" "$dest"; then
    mv "$dest" "$dest.backup"
    warn "moved existing $dest to $dest.backup"
  fi
  mv "$tmp" "$dest"
  chmod "$mode" "$dest"
}

# --- Packages ----------------------------------------------------------------

log "Installing packages"
brew tap koekeishiya/formulae
brew tap FelixKratz/formulae
brew install koekeishiya/formulae/yabai koekeishiya/formulae/skhd \
  FelixKratz/formulae/borders FelixKratz/formulae/sketchybar \
  lua switchaudio-osx
brew install --cask sf-symbols font-sketchybar-app-font

# --- yabai -------------------------------------------------------------------

log "Writing $CONFIG/yabai/yabairc"
install_file "$CONFIG/yabai/yabairc" 755 <<'EOF'
#!/usr/bin/env sh
# Generated by scripts/setup-brew-wm.sh (mirrors darwin/configuration.nix).

yabai -m config layout                bsp
yabai -m config auto_balance          on
yabai -m config split_ratio           0.50
yabai -m config window_placement      second_child
yabai -m config focus_follows_mouse   off
yabai -m config mouse_follows_focus   on
yabai -m config mouse_action1         move
yabai -m config mouse_action2         resize
yabai -m config mouse_drop_action     swap
yabai -m config top_padding           10
yabai -m config bottom_padding        10
yabai -m config left_padding          10
yabai -m config right_padding         10
yabai -m config window_gap            10
yabai -m config external_bar          all:40:0
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config window_shadow         on
yabai -m config window_opacity        off

yabai -m rule --add app='^Emacs$' manage=on
yabai -m rule --add title='Preferences' manage=off sub-layer=above
yabai -m rule --add title='Library' manage=off sub-layer=above
yabai -m rule --add app='^System Preferences$' manage=off sub-layer=above
yabai -m rule --add app='Activity Monitor' manage=off sub-layer=above
yabai -m rule --add app='^System Information$' manage=off sub-layer=above
EOF

# --- skhd --------------------------------------------------------------------

log "Writing $CONFIG/skhd/skhdrc"
install_file "$CONFIG/skhd/skhdrc" 644 <<'EOF'
# Generated by scripts/setup-brew-wm.sh (mirrors darwin/configuration.nix).

shift + alt - r : skhd --restart-service; brew services restart sketchybar
shift + alt - y : yabai --restart-service

shift + alt - t : open -na Ghostty

shift + alt - f : open -na "Google Chrome"

alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

shift + alt - 1 : yabai -m window --space 1
shift + alt - 2 : yabai -m window --space 2
shift + alt - 3 : yabai -m window --space 3
shift + alt - 4 : yabai -m window --space 4
shift + alt - 5 : yabai -m window --space 5
shift + alt - 6 : yabai -m window --space 6
shift + alt - 7 : yabai -m window --space 7
shift + alt - 8 : yabai -m window --space 8
shift + alt - 9 : yabai -m window --space 9
shift + alt - 0 : yabai -m window --space 10

alt - r : yabai -m space --rotate 90

ctrl + alt - h : \
    yabai -m window --resize left:-100:0 ; \
    yabai -m window --resize right:-100:0

ctrl + alt - j : \
    yabai -m window --resize bottom:0:100 ; \
    yabai -m window --resize top:0:100

ctrl + alt - k : \
    yabai -m window --resize top:0:-100 ; \
    yabai -m window --resize bottom:0:-100

ctrl + alt - l : \
    yabai -m window --resize right:100:0 ; \
    yabai -m window --resize left:100:0

alt - s : yabai -m window --toggle split

alt - f : yabai -m window --toggle zoom-fullscreen

alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

alt - c : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

shift + ctrl + alt - h : yabai -m window --insert west
shift + ctrl + alt - j : yabai -m window --insert south
shift + ctrl + alt - k : yabai -m window --insert north
shift + ctrl + alt - l : yabai -m window --insert east

shift + alt - n : osascript -e 'tell application "Spotify" to Next Track'
shift + alt - p : osascript -e 'tell application "Spotify" to Previous Track'

shift + ctrl + alt - up : osascript -e 'tell application "Spotify" to set sound volume to 100'
shift + ctrl + alt - down : osascript -e 'tell application "Spotify" to set sound volume to 20'

shift + alt - down : osascript -e "set volume output volume ((output volume of (get volume settings)) - 3)"
shift + alt - up : osascript -e "set volume output volume ((output volume of (get volume settings)) + 3)"

shift + ctrl + alt - c : echo "https://calendly.com/tpmeadows1/30min" | pbcopy

shift + alt - space : osascript -e 'tell application "Spotify" to playpause'

shift + ctrl - 1 : m1ddc display 1 set input 17
shift + ctrl - 2 : m1ddc display 1 set input 15
shift + ctrl - 3 : m1ddc display 1 set input 27

ctrl + alt - 1  : yabai -m display --focus 1
ctrl + alt - 2  : yabai -m display --focus 2

lalt - space : yabai -m window --toggle float; sketchybar --trigger window_focus
shift + lalt - f : yabai -m window --toggle zoom-fullscreen; sketchybar --trigger window_focus
lalt - f : yabai -m window --toggle zoom-parent; sketchybar --trigger window_focus
EOF

# --- JankyBorders ------------------------------------------------------------

log "Writing $CONFIG/borders/bordersrc"
install_file "$CONFIG/borders/bordersrc" 755 <<'EOF'
#!/bin/bash
# Generated by scripts/setup-brew-wm.sh (mirrors darwin/configuration.nix).

options=(
  width=9.0
  hidpi=on
  active_color=0xffAFDCA4
  inactive_color=0xffaaaaaa
  style=round
  ax_focus=on
  order=below
)

borders "${options[@]}"
EOF

# --- sketchybar --------------------------------------------------------------

log "Linking $CONFIG/sketchybar -> $REPO/darwin/modules/sketchybar/config"
target="$REPO/darwin/modules/sketchybar/config"
if [[ -e "$CONFIG/sketchybar" && "$(readlink "$CONFIG/sketchybar" || true)" != "$target" ]]; then
  rm -rf "$CONFIG/sketchybar.backup"
  mv "$CONFIG/sketchybar" "$CONFIG/sketchybar.backup"
  warn "moved existing $CONFIG/sketchybar to $CONFIG/sketchybar.backup"
fi
ln -sfn "$target" "$CONFIG/sketchybar"

if [[ ! -f "$HOME/.local/share/sketchybar_lua/sketchybar.so" ]]; then
  log "Installing SbarLua"
  tmp="$(mktemp -d)"
  git clone --depth 1 https://github.com/FelixKratz/SbarLua.git "$tmp/SbarLua"
  make -C "$tmp/SbarLua" install
  rm -rf "$tmp"
fi

# --- macOS defaults ----------------------------------------------------------

# sketchybar replaces the menu bar (yabai reserves 40px for it via external_bar).
log "Auto-hiding the macOS menu bar"
defaults write NSGlobalDomain _HIHideMenuBar -bool true

# --- Services ----------------------------------------------------------------

log "Starting services"
yabai --restart-service 2>/dev/null || yabai --start-service
skhd --restart-service 2>/dev/null || skhd --start-service
brew services restart borders
brew services restart sketchybar

# --- Manual steps ------------------------------------------------------------

if ! compgen -G "$HOME/Library/Fonts/SF-Pro*" >/dev/null && ! compgen -G "/Library/Fonts/SF-Pro*" >/dev/null; then
  warn "SF Pro / SF Mono not found: install them from https://developer.apple.com/fonts/ (the Homebrew casks are broken)"
fi

cat <<EOF

Done. Remaining manual steps:
  - System Settings > Privacy & Security > Accessibility: allow yabai, skhd and
    $target/helpers/menus/bin/menus (sketchybar's menu widget), then run
    \`yabai --restart-service && skhd --restart-service\`.
  - Log out and back in if the menu bar doesn't auto-hide.
EOF
